#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

 if [[ $(xrandr -q | grep "Virtual1 connected") ]];
   then
      xrandr --output Virtual1  --primary --mode 1440x900 --pos 0x0  --rotate normal \
             --output DVI-I-1 --off \
             --output DVI-I-2 --off 
      bspc monitor Virtual1 -d I II III IV V VI VII VIII IX
   fi

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#### Auto Start
sxhkd &
dunst &
numlockx &
setxkbmap br &
xfce4-clipman &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh --cuts &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --bg-fill --no-fehbg --randomize $HOME/Imagens/Wallpapers/* &
picom -b --config $HOME/.config/picom/picom.conf --experimental-backends &


#### Others
vmware-user-suid-wrapper &

